import firebase from 'firebase/app';
import 'firebase/firestore';
import config from './firestoreConfig';

const firestore = {
  connect() {
    // if firebase hasn't been initialized yet, then do so
    if (!firebase.apps.length) {
      firebase.initializeApp(config);
    }

    const db = firebase.firestore();

    return db;
  },
  async createDocument(collectionName, documentName, value) {
    try {
      const db = this.connect();

      // if document id is not specified, then the document id
      // will be auto-generated by firebase
      if (!documentName) {
        const collection = await db.collection(collectionName).get();
        const documents = collection.docs;
        const objKey = Object.keys(value)[0];
        const objValue = Object.values(value)[0];

        // if there are more than one document in that collection
        // we need to make sure that only one document has a field
        // with the provided parameter value
        if (documents.length > 0) {
          const fieldExists = documents.some(
            (doc) => doc.get(objKey) === objValue,
          );

          if (fieldExists) {
            return false;
          }

          const { documentId } = await db
            .collection(collectionName)
            .add(value);

          return { created: true, documentId };
        }

        const { documentId } = await db.collection(collectionName).add(value);

        return { created: true, documentId };
      }

      await db.collection(collectionName).doc(documentName).set(value);

      return { created: true };
    } catch (err) {
      console.log(
        `There was an error while trying to create the document: ${err}`,
      );
      return false;
    }
  },
  async updateDocumentField(path, field, value) {
    try {
      const db = this.connect();
      const [collection, document] = path.split('/');

      db.collection(collection)
        .doc(document)
        .update({ [field]: value });

      return true;
    } catch (err) {
      console.log(
        `There was an error while trying to update the specified field: ${
          err}`,
      );
      return false;
    }
  },
};

export default firestore;
